### ISSUE TITLE
Configuration -> Mediation Throws the following error

### ISSUE THREAD

**Issue by uppaljs** [WebDataConsulting/billing#14]
An unhandled exception has occurred.
If the problem persists, please contact jBilling support and include a copy of the error report below.
ERROR 500
URI 
Message Cannot get property 'id' on null object
Caused by   Error processing GroovyPageView: Error executing tag sitemesh:captureContent: Error executing tag <g:render>: Error executing tag <g:remoteLink>: Error evaluating expression ['(' + configReader.id + ') ' + configReader.type?.getDescription(session.language_id)] on line [49]: Cannot get property 'id' on null object
Source  Message
# Stack Trace

org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag sitemesh:captureContent: Error executing tag <g:render>: Error executing tag <g:remoteLink>: Error evaluating expression ['(' + configReader.id + ') ' + configReader.type?.getDescription(session.language_id)] on line [49]: Cannot get property 'id' on null object
    at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
    at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag sitemesh:captureContent: Error executing tag <g:render>: Error executing tag <g:remoteLink>: Error evaluating expression ['(' + configReader.id + ') ' + configReader.type?.getDescription(session.language_id)] on line [49]: Cannot get property 'id' on null object
    at home_uppal_wd_billing_grails_app_views_mediationConfig_list_gsp$_run_closure2.doCall(home_uppal_wd_billing_grails_app_views_mediationConfig_list_gsp:32)
    at home_uppal_wd_billing_grails_app_views_mediationConfig_list_gsp.run(home_uppal_wd_billing_grails_app_views_mediationConfig_list_gsp:46)
    ... 5 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:render>: Error executing tag <g:remoteLink>: Error evaluating expression ['(' + configReader.id + ') ' + configReader.type?.getDescription(session.language_id)] on line [49]: Cannot get property 'id' on null object
    at home_uppal_wd_billing_grails_app_views_mediationConfig_list_gsp$_run_closure2_closure7.doCall(home_uppal_wd_billing_grails_app_views_mediationConfig_list_gsp:29)
    ... 7 more
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:remoteLink>: Error evaluating expression ['(' + configReader.id + ') ' + configReader.type?.getDescription(session.language_id)] on line [49]: Cannot get property 'id' on null object
    at home_uppal_wd_billing_grails_app_views_mediationConfig__configs_gsp.run(home_uppal_wd_billing_grails_app_views_mediationConfig__configs_gsp:51)
    ... 8 more
Caused by: org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error evaluating expression ['(' + configReader.id + ') ' + configReader.type?.getDescription(session.language_id)] on line [49]: Cannot get property 'id' on null object
    at home_uppal_wd_billing_grails_app_views_mediationConfig__configs_gsp$_run_closure21.doCall(home_uppal_wd_billing_grails_app_views_mediationConfig__configs_gsp:48)
    ... 9 more
Caused by: java.lang.NullPointerException: Cannot get property 'id' on null object
    at home_uppal_wd_billing_grails_app_views_mediationConfig__configs_gsp$_run_closure21_closure37.doCall(home_uppal_wd_billing_grails_app_views_mediationConfig__configs_gsp:48)
    ... 10 more

**Comment by vikasbo** [comment]
Hello @uppaljs  - Can you confirm the source of your jBilling CE Edition that causes the above issue? Thanks.
